SET SERVEROUTPUT ON
DECLARE 
 CODENT_AUX CERSATPRE.PCDT082.CODENT%TYPE;
 CODESTCTA_AUX CERSATPRE.PCDT082.CODESTCTA%TYPE;
 
 CURSOR C082 IS SELECT * FROM CERSATPRE.PCDT082 
 WHERE CODENT = CODENT_AUX AND CODESTCTA = CODESTCTA_AUX
 ORDER BY CODENT, CODGRU, CODCCN, TIPFRAN, INDAPLDEBCRE, TIPOFAC, CODCONECO, TIPOLIN, CODESTCTA, CODACTEMP, CODMONEDA, PRODUCTO, SUBPRODU;
 
 FILA CERSATPRE.PCDT082%ROWTYPE;
BEGIN
  CODENT_AUX := '0005';
  CODESTCTA_AUX := 0;
  OPEN C082;
  
  LOOP
    FETCH C082 INTO FILA;
    EXIT WHEN C082%NOTFOUND;
    
    DBMS_OUTPUT.PUT_LINE(FILA.CODENT|| FILA.CODGRU|| FILA.CODCCN|| FILA.TIPFRAN|| FILA.INDAPLDEBCRE||
    FILA.TIPOFAC|| FILA.CODCONECO|| FILA.TIPOLIN|| FILA.CODESTCTA|| FILA.CODACTEMP|| FILA.CODMONEDA||
    FILA.PRODUCTO|| FILA.SUBPRODU|| FILA.NUMCTASAT|| FILA.CUENTAHABER|| FILA.SIGNOSAT|| FILA.OFIIMPDEB||
    FILA.OFIIMPHAB|| FILA.FECALTA|| FILA.FECINI||FILA.FECFIN|| FILA.CTADEBETPMP|| FILA.CTAHABERTPMP||
    FILA.CODENTUMO|| FILA.CODOFIUMO|| FILA.USUARIOUMO|| FILA.CODTERMUMO|| FILA.CONTCUR);
    
  END LOOP;
  
  CLOSE C082;
  
END;
